### ISSUE TITLE
Improve the README.md Documentation

### ISSUE THREAD

**Issue by OshadhaVimuB** [Sujas-Aggarwal/Chess#1]
### Proposed Changes:

- Add a more detailed introduction
- Improve installation instructions
- Include a "How to Play" section
- Contributing Guidelines

### Acceptance Criteria

The README.md file contains sections for:

- Introduction
- Prerequisites and Installation
- How to Play
- Contributing

Kindly assign me this under **Hacktoberfest** 2024

**Comment by Sujas-Aggarwal** [comment]
Go for it
