### ISSUE TITLE
Increase Code Modularity

### ISSUE THREAD

**Issue by Sujas-Aggarwal** [Sujas-Aggarwal/Chess#5]
The Current file is in a single file form which is not very easy to maintain, hence we need to divide the code into different files

**Comment by Sujas-Aggarwal** [comment]
@Roya1king Can you take on this?

**Comment by nikhiljangra264** [comment]
I can work on this. Please co-assign me.

**Comment by Sujas-Aggarwal** [comment]
Go for it @nikhiljangra264
