### ISSUE TITLE
ISSUE: Cross-Platform Incompatibility in File Path Handling

### ISSUE THREAD

**Issue by nikhiljangra264** [Sujas-Aggarwal/Chess#7]
### **Description**:
The current implementation of the file paths for loading audio files in the game (e.g., `'Assets/Sounds/capture.mp3'`) is not compatible across different operating systems.
For example i am running this on my Linux laptop and I am getting a FileNotFoundError

### **Screenshot**:
![Screenshot_2024-10-24_19_27_17](https://github.com/user-attachments/assets/11b43296-de38-4e19-b053-d98c13717258)

**Comment by nikhiljangra264** [comment]
I would like to work on it @Sujas-Aggarwal

**Comment by Sujas-Aggarwal** [comment]
Go for it @nikhiljangra264
